# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.3
language: objective-c
env:
  - SWIFT_VERSION=5.1
install:
  - bundle install
before_script:
  - bundle exec pod lib lint --allow-warnings
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/SQRichTextEditor.xcworkspace -scheme SQRichTextEditor-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
